import type { LessonCardDef, RelationshipCombineRubric } from "./lesson-cards";

type Item = {
  first: string;
  second: string;
  relationship: RelationshipCombineRubric["relationship"];
  conjunctions: string[];
  answer: string;
  tokens: string[];
  explanation: string;
};

const items: Item[] = [
  { first: "Fuel prices rose sharply.", second: "Airlines increased their ticket prices.", relationship: "Cause/Effect", conjunctions: ["because", "since", "as"], answer: "Airlines increased their ticket prices because fuel prices rose sharply.", tokens: ["fuel", "prices", "airlines", "ticket"], explanation: "Cause/Effect is the correct relationship: the rise in fuel prices is the cause, and the increase in airline ticket prices is the effect. 'Because' introduces the cause after the main clause, so no comma is needed before it." },
  { first: "The region experienced severe flooding.", second: "Thousands of residents were evacuated.", relationship: "Cause/Effect", conjunctions: ["because", "since", "as"], answer: "Thousands of residents were evacuated because the region experienced severe flooding.", tokens: ["region", "flooding", "residents", "evacuated"], explanation: "The flooding caused the evacuation, so the relationship is Cause/Effect. Here, 'because' introduces the reason after the result. A trailing because-clause is normally not separated from the main clause by a comma." },
  { first: "The company automated its production line.", second: "Manufacturing costs fell by twenty percent.", relationship: "Cause/Effect", conjunctions: ["since", "because", "as"], answer: "Since the company automated its production line, manufacturing costs fell by twenty percent.", tokens: ["company", "automated", "manufacturing", "twenty percent"], explanation: "Automation is presented as the cause of the reduction in manufacturing costs. 'Since' introduces that cause at the beginning, making the opening clause dependent; a comma must therefore separate it from the main result clause." },
  { first: "Interest rates were cut twice this year.", second: "Consumer borrowing has increased.", relationship: "Cause/Effect", conjunctions: ["because", "since", "as"], answer: "Consumer borrowing has increased because interest rates were cut twice this year.", tokens: ["interest rates", "twice", "consumer", "borrowing"], explanation: "The interest-rate cuts explain why borrowing increased, so this is Cause/Effect. With the result first and the because-clause second, the sentence flows directly without a comma before 'because'." },
  { first: "The bridge was found to be structurally unsound.", second: "Engineers closed it to all traffic.", relationship: "Cause/Effect", conjunctions: ["since", "because", "as"], answer: "Since the bridge was found to be structurally unsound, engineers closed it to all traffic.", tokens: ["bridge", "unsound", "engineers", "traffic"], explanation: "The unsafe condition of the bridge caused the closure. 'Since' turns the first idea into a dependent cause clause. Because that clause comes first, it must be followed by a comma before the result clause." },
  { first: "Local farmers adopted drip irrigation.", second: "Crop yields improved substantially.", relationship: "Cause/Effect", conjunctions: ["because", "since", "as"], answer: "Crop yields improved substantially because local farmers adopted drip irrigation.", tokens: ["farmers", "irrigation", "crop", "yields"], explanation: "Adopting drip irrigation is the cause, while improved crop yields are the effect. 'Because' clearly marks the causal clause; when that clause follows the main clause, no comma is normally required." },
  { first: "A severe storm disrupted air traffic across the region.", second: "The airline cancelled dozens of flights.", relationship: "Cause/Effect", conjunctions: ["because", "since", "as"], answer: "The airline cancelled dozens of flights because a severe storm disrupted air traffic across the region.", tokens: ["storm", "air traffic", "airline", "flights"], explanation: "The storm's disruption caused the cancellations, establishing Cause/Effect. The because-clause supplies essential reason information after the result, so it joins the main clause without a comma." },
  { first: "The museum extended its opening hours.", second: "Visitor numbers grew considerably.", relationship: "Cause/Effect", conjunctions: ["since", "because", "as"], answer: "Since the museum extended its opening hours, visitor numbers grew considerably.", tokens: ["museum", "hours", "visitor", "grew"], explanation: "The extended hours explain the growth in visitor numbers. A fronted 'since' clause is dependent and cannot stand alone; the comma marks its boundary before the independent result clause." },
  { first: "The northern factory relies entirely on solar power.", second: "The southern plant still depends on coal.", relationship: "Contrast", conjunctions: ["whereas", "while"], answer: "The northern factory relies entirely on solar power, whereas the southern plant still depends on coal.", tokens: ["northern", "solar", "southern", "coal"], explanation: "The clauses compare opposite energy sources, so the relationship is Contrast. 'Whereas' directly balances the northern factory against the southern plant, and a comma is used before it when it links these two complete contrasting clauses." },
  { first: "The exam was extremely difficult.", second: "Most students still managed to pass.", relationship: "Contrast", conjunctions: ["although", "though", "even though"], answer: "Although the exam was extremely difficult, most students still managed to pass.", tokens: ["exam", "difficult", "students", "pass"], explanation: "Passing despite a difficult exam creates a concessive contrast. 'Although' introduces the unexpected obstacle. Since the although-clause comes first, a comma is required before the main clause." },
  { first: "The new policy was widely criticized.", second: "It remained in effect for another year.", relationship: "Contrast", conjunctions: ["though", "although", "even though"], answer: "Though the new policy was widely criticized, it remained in effect for another year.", tokens: ["policy", "criticized", "effect", "year"], explanation: "The policy remaining in effect is unexpected in light of the criticism, which makes this a concessive Contrast. The opening dependent clause beginning with 'Though' must be followed by a comma." },
  { first: "City centers offer excellent public transport.", second: "Suburban areas remain heavily dependent on private cars.", relationship: "Contrast", conjunctions: ["whereas", "while"], answer: "City centers offer excellent public transport, whereas suburban areas remain heavily dependent on private cars.", tokens: ["city", "transport", "suburban", "cars"], explanation: "The sentence contrasts transport conditions in two locations. 'Whereas' is appropriate for a direct comparison of unlike facts, and a comma precedes it when both sides are complete clauses." },
  { first: "The company posted record profits this quarter.", second: "It announced significant staff layoffs.", relationship: "Contrast", conjunctions: ["although", "though", "even though"], answer: "Although the company posted record profits this quarter, it announced significant staff layoffs.", tokens: ["company", "profits", "quarter", "layoffs"], explanation: "Layoffs are unexpected after record profits, creating concessive Contrast. 'Although' subordinates the positive financial fact, and the comma closes that fronted dependent clause before the surprising main clause." },
  { first: "The treatment is highly effective.", second: "It remains prohibitively expensive for most patients.", relationship: "Contrast", conjunctions: ["though", "although", "even though"], answer: "The treatment is highly effective, though it remains prohibitively expensive for most patients.", tokens: ["treatment", "effective", "expensive", "patients"], explanation: "Effectiveness is contrasted with lack of affordability. A trailing 'though' clause adds a concessive limitation to the first statement; the comma signals the contrast between the two complete ideas." },
  { first: "Some countries have banned single-use plastics entirely.", second: "Others have taken no action at all.", relationship: "Contrast", conjunctions: ["whereas", "while"], answer: "Some countries have banned single-use plastics entirely, whereas others have taken no action at all.", tokens: ["countries", "plastics", "others", "action"], explanation: "The clauses compare opposing policies, so Contrast is the logical relationship. 'Whereas' is designed for this balanced comparison and is preceded by a comma between the two independent clauses." },
  { first: "The negotiations lasted for over a year.", second: "No final agreement was reached.", relationship: "Contrast", conjunctions: ["although", "though", "even though"], answer: "Although the negotiations lasted for over a year, no final agreement was reached.", tokens: ["negotiations", "year", "agreement", "reached"], explanation: "A long negotiation would normally be expected to produce an agreement, but it did not. 'Although' marks this concession, and its fronted dependent clause requires a comma before the main clause." },
  { first: "The government approves additional funding.", second: "The hospital will open a new wing next year.", relationship: "Condition", conjunctions: ["if", "provided that", "as long as"], answer: "If the government approves additional funding, the hospital will open a new wing next year.", tokens: ["government", "funding", "hospital", "wing"], explanation: "The hospital opening depends on funding approval, so this is a Condition. 'If' introduces the requirement. Because the if-clause comes first, a comma separates it from the predicted result." },
  { first: "Interest rates remain stable.", second: "The housing market is expected to recover.", relationship: "Condition", conjunctions: ["as long as", "provided that", "if"], answer: "As long as interest rates remain stable, the housing market is expected to recover.", tokens: ["interest rates", "stable", "housing", "recover"], explanation: "Recovery is expected only under the continuing condition of stable rates. 'As long as' emphasizes that the condition must remain true, and a comma follows the fronted conditional clause." },
  { first: "The company will not expand overseas.", second: "Local demand increases significantly.", relationship: "Condition", conjunctions: ["unless"], answer: "The company will not expand overseas unless local demand increases significantly.", tokens: ["company", "expand", "local", "demand"], explanation: "Expansion depends on local demand increasing, so the relationship is Condition. 'Unless' means 'if not': the company will not expand if the required increase does not occur. No comma is needed before this trailing essential condition." },
  { first: "Students submit their applications by the deadline.", second: "They will be considered for the scholarship.", relationship: "Condition", conjunctions: ["provided that", "if", "as long as"], answer: "Provided that students submit their applications by the deadline, they will be considered for the scholarship.", tokens: ["students", "applications", "deadline", "scholarship"], explanation: "Submitting by the deadline is the requirement for consideration, making this a Condition. 'Provided that' explicitly means 'only on the condition that'; its fronted clause is followed by a comma." },
  { first: "The dam is not reinforced.", second: "It may fail during the next major flood.", relationship: "Condition", conjunctions: ["unless"], answer: "The dam may fail during the next major flood unless it is reinforced.", tokens: ["dam", "fail", "flood", "reinforced"], explanation: "Reinforcement is the condition that can prevent failure. 'Unless it is reinforced' means 'if it is not reinforced' and accurately preserves the negative condition. The trailing unless-clause does not need a comma." },
  { first: "The negotiations continue to stall.", second: "The merger deadline will need to be extended.", relationship: "Condition", conjunctions: ["if", "provided that"], answer: "If the negotiations continue to stall, the merger deadline will need to be extended.", tokens: ["negotiations", "stall", "merger", "deadline"], explanation: "Extending the deadline depends on continued delay in the negotiations. 'If' introduces this possible condition, and the fronted if-clause takes a comma before the consequence." },
  { first: "Both parties formally terminate the contract.", second: "It remains legally binding.", relationship: "Condition", conjunctions: ["unless"], answer: "The contract remains legally binding unless both parties formally terminate it.", tokens: ["parties", "terminate", "contract", "binding"], explanation: "The contract stays binding except under one condition: formal termination by both parties. 'Unless' means 'except if' and therefore expresses the required negative condition without a comma in this trailing position." },
  { first: "The new subway line opened.", second: "Commute times in the city fell dramatically.", relationship: "Time", conjunctions: ["since", "after"], answer: "Since the new subway line opened, commute times in the city fell dramatically.", tokens: ["subway", "opened", "commute", "fell"], explanation: "The opening establishes the point in time after which commute times fell, so this is Time. 'Since' introduces that starting point, and its fronted dependent clause is followed by a comma." },
  { first: "The plane reaches cruising altitude.", second: "Passengers may remove their seatbelts.", relationship: "Time", conjunctions: ["once", "after", "when"], answer: "Once the plane reaches cruising altitude, passengers may remove their seatbelts.", tokens: ["plane", "altitude", "passengers", "seatbelts"], explanation: "Seatbelts may be removed only after a specific moment, establishing a Time relationship. 'Once' means 'as soon as that event has happened'; the fronted time clause requires a comma." },
  { first: "Researchers ran extensive safety trials.", second: "The drug was approved for public use.", relationship: "Time", conjunctions: ["before"], answer: "Researchers ran extensive safety trials before the drug was approved for public use.", tokens: ["researchers", "trials", "drug", "approved"], explanation: "The trials occurred earlier than approval, so the relationship is Time. 'Before' clearly orders the events. Because the before-clause follows the main clause, no comma is normally needed." },
  { first: "The factory closed permanently.", second: "Unemployment in the town rose sharply.", relationship: "Time", conjunctions: ["after", "once", "when"], answer: "After the factory closed permanently, unemployment in the town rose sharply.", tokens: ["factory", "closed", "unemployment", "town"], explanation: "The sentence places the rise in unemployment later than the factory closure. 'After' expresses this Time sequence, and a comma separates the opening dependent time clause from the main clause." },
  { first: "The concert begins.", second: "Latecomers will not be admitted to the venue.", relationship: "Time", conjunctions: ["once", "after", "when"], answer: "Once the concert begins, latecomers will not be admitted to the venue.", tokens: ["concert", "begins", "latecomers", "venue"], explanation: "Admission changes at the moment the concert begins, making this a Time relationship. 'Once' marks that threshold, and its fronted dependent clause must be followed by a comma." },
  { first: "The treaty was signed.", second: "Trade between the two nations has grown steadily.", relationship: "Time", conjunctions: ["since", "after"], answer: "Trade between the two nations has grown steadily since the treaty was signed.", tokens: ["treaty", "signed", "trade", "nations"], explanation: "The treaty signing is the starting point for the continuing growth in trade. 'Since' expresses elapsed time from that point to the present, and no comma is needed before a trailing essential since-clause." },
  { first: "The construction crew inspects the site thoroughly.", second: "Work on the new building begins.", relationship: "Time", conjunctions: ["before"], answer: "The construction crew inspects the site thoroughly before work on the new building begins.", tokens: ["crew", "inspects", "site", "building"], explanation: "The inspection must occur earlier than the start of building work, so the relationship is Time. 'Before' establishes the sequence and joins the trailing time clause without a comma." },
];

const relationshipOptions = ["Cause/Effect", "Contrast", "Condition", "Time"];

export const relationshipCombiningCard: LessonCardDef = {
  slug: "identify-relationship-combine-30q",
  title: "Identify the Relationship, Then Combine",
  description: "Identify the logical relationship, choose a suitable subordinating conjunction, and combine each clause pair correctly. Each item must be correct before the next unlocks.",
  kind: "combine_seq",
  lesson: [
    { kind: "heading", text: "Three-Step Clause Analysis" },
    { kind: "text", text: "For every pair, first identify the logical relationship, then choose a subordinating conjunction that expresses it, and finally combine both clauses into one complete sentence." },
    { kind: "table", headers: ["Relationship", "Common conjunctions", "Meaning"], rows: [
      ["Cause/Effect", "because, since, as", "One event explains why another happened."],
      ["Contrast", "although, though, whereas, while", "The ideas differ or one result is unexpected."],
      ["Condition", "if, unless, provided that, as long as", "One event depends on a requirement."],
      ["Time", "before, after, once, since, when", "The clauses are ordered in time."],
    ] },
    { kind: "heading", text: "Punctuation" },
    { kind: "bullets", items: [
      "Use a comma after a dependent clause that begins the sentence.",
      "Do not normally add a comma before a trailing because, if, unless, before, or after clause.",
      "Use a comma before whereas, while, although, or though when it introduces a contrasting clause after a complete main clause.",
      "Keep every important fact from both original clauses in one sentence.",
    ] },
    { kind: "review", title: "Before checking", items: ["Relationship selected", "Suitable conjunction entered", "Conjunction used in the sentence", "Both ideas retained", "Punctuation checked"] },
  ],
  questions: items.map((item, index) => ({
    prompt: `${item.first}\n${item.second}\nComplete all three steps: identify the relationship, choose a suitable subordinating conjunction, and combine the clauses.`,
    answer: item.answer,
    hints: [],
    source: `Question ${index + 1}`,
    relationshipRubric: {
      relationship: item.relationship,
      acceptableConjunctions: item.conjunctions,
      requiredTokens: item.tokens,
    },
    explanation: item.explanation,
    relationshipOptions,
  })),
};
