import "server-only";
import type { LessonCardDef, LessonQuestion } from "./lesson-cards";
import { DICTATION_ITEMS, DICTATION_CATEGORY_NAMES } from "./word-vault-challenge-content";

/**
 * SERVER-ONLY MODULE — DO NOT IMPORT FROM CLIENT CODE.
 *
 * "Listening Dictation: Type What You Hear" — Activity A of the Word Vault
 * Listening & Story Challenge.
 *
 * A British (en-GB) voice reads one sentence containing a Word Vault target
 * word; the student types the whole sentence from memory. The sentence and
 * the target word are never shown before marking — the sentence travels to
 * the browser only so the speech synthesiser can read it aloud, and grading
 * happens here on the server against the hidden key.
 *
 * The 120 items come from Word_Vault_Listening_and_Story_Challenge.docx
 * (Section 8), regenerated by scripts/generate_word_vault_listening_content.py.
 */

/**
 * The 120 items as generic lesson questions. `prompt` is deliberately empty —
 * the sentence must never be rendered as text — while `answer` holds the
 * hidden target word used for grading and the word count.
 */
const questions: LessonQuestion[] = DICTATION_ITEMS.map((item) => ({
  prompt: "",
  answer: item.target,
  hints: [
    `Sound the word out syllable by syllable. Its phonetic transcription is ${item.ipa}.`,
    "Check every letter — a silent vowel or a doubled letter is easy to miss.",
  ],
  source: DICTATION_CATEGORY_NAMES[item.category] || `Category ${item.category}`,
}));

export const spellingListeningCard: LessonCardDef = {
  slug: "word-vault-listening",
  title: "Listening Dictation: Type What You Hear",
  description:
    "A British voice reads a sentence containing one Word Vault word. Type the whole sentence from memory — the sentence and the word are never shown until you are marked. Section practice or the full 120-word test, with every retry tracked.",
  kind: "spelling_listening",
  lesson: [
    { kind: "heading", text: "🎧 Listening Dictation — how it works" },
    {
      kind: "text",
      text: "A British English (en-GB) voice reads one sentence at a time. Each sentence contains one of the 120 Word Vault words. Listen carefully, then type the whole sentence exactly as you heard it.",
    },
    {
      kind: "bullets",
      items: [
        "🔊 Play the sentence as often as you like — use Slow to hear every word separated.",
        "⌨️ Type the whole sentence, not just the target word. Spelling, not speed, is what counts.",
        "✅ Get the sentence perfect for a full mark; get the target word right and the sentence mark is kept even if another word slips.",
        "🔁 You get two tries per sentence. After the second miss the correct sentence is shown with the word highlighted.",
        "🇬🇧 British spelling only — colour, centre, organise, travelling. American spellings are marked wrong.",
        "📊 Every attempt is recorded, so your review list follows you between sessions.",
      ],
    },
    { kind: "subheading", text: "The six Word Vault categories" },
    {
      kind: "bullets",
      items: Object.entries(DICTATION_CATEGORY_NAMES).map(
        ([n, name]) => `${n}. ${name} — 20 words`
      ),
    },
    {
      kind: "review",
      title: "⚡ Dictation tips",
      items: [
        "Listen once for the meaning, then again for the spelling of the hard word.",
        "Watch the classic traps: a dropped vowel (every, family) or a swallowed letter (Wednesday).",
        "When the voice reaches a word with a silent letter, picture the word before you type.",
        "Re-type the whole sentence — one missing word marks the sentence, not just the misspelling.",
      ],
    },
  ],
  questions,
};
