import "server-only";
import type { LessonCardDef, LessonQuestion } from "./lesson-cards";
import { DICTATION_ITEMS, STORY_CHAPTERS } from "./word-vault-challenge-content";

/**
 * SERVER-ONLY MODULE — DO NOT IMPORT FROM CLIENT CODE.
 *
 * "Story Challenge: Listen & Fill the Gaps" — Activity B of the Word Vault
 * Listening & Story Challenge.
 *
 * A British (en-GB) voice narrates one chapter of "The Map in the Camera"
 * while the text appears in time with the reading. Whenever one of the 120
 * Word Vault words comes up, the voice says the word and the screen shows an
 * empty box of fixed width — the student types the word they heard. The gap
 * word is sent to the browser only so the speech synthesiser can pronounce it
 * in its place; it is never rendered as text, and grading happens here on the
 * server against the hidden key.
 *
 * The 6 chapters / 120 gaps come from Word_Vault_Listening_and_Story_
 * Challenge.docx (Section 9), regenerated by
 * scripts/generate_word_vault_listening_content.py.
 */

const questions: LessonQuestion[] = STORY_CHAPTERS.flatMap((chapter) =>
  chapter.paragraphs.flatMap((chunks) =>
    chunks
      .filter((c): c is Extract<typeof c, { type: "gap" }> => c.type === "gap")
      .map((gap) => ({
        prompt: "",
        answer: gap.word,
        hints: [
          "Replay the word on its own, slowly, then say it in your head as you type.",
          "Check the ending — a silent letter or a doubled letter is easy to miss.",
        ],
        source: `Chapter ${chapter.chapter}: ${chapter.title}`,
      }))
  )
);

/** Chapter titles, exposed so the API can describe a chapter without the gaps. */
export const STORY_CHAPTER_TITLES: { chapter: number; title: string }[] = STORY_CHAPTERS.map(
  (c) => ({ chapter: c.chapter, title: c.title })
);

/** A quick lookup from a gap's word ID to its Word Vault target word. */
export const WORD_BY_ID: Record<number, { target: string; typicalError: string }> = Object.fromEntries(
  DICTATION_ITEMS.map((item) => [item.id, { target: item.target, typicalError: item.typicalError }])
);

/** The 120 story gap IDs in reading order, one per Word Vault word. */
export const STORY_GAP_IDS: number[] = STORY_CHAPTERS.flatMap((chapter) =>
  chapter.paragraphs.flatMap((chunks) =>
    chunks.filter((c) => c.type === "gap").map((c) => (c as { id: number }).id)
  )
);

export const spellingStoryCard: LessonCardDef = {
  slug: "word-vault-story",
  title: "Story Challenge: Listen & Fill the Gaps",
  description:
    "A British voice narrates six chapters of “The Map in the Camera”. Whenever a Word Vault word is spoken, the screen hides it behind a blank box — type the word you heard. 6 chapters, 120 gaps; the narration waits for you at every gap.",
  kind: "spelling_story",
  lesson: [
    { kind: "heading", text: "📖 Story Challenge — how it works" },
    {
      kind: "text",
      text: "Listen as a British English (en-GB) voice reads the story aloud. The text appears on screen in time with the reading — but whenever one of the 120 Word Vault words comes up, you hear it while the screen shows an empty box.",
    },
    {
      kind: "bullets",
      items: [
        "🎧 Press Play and follow the story as it is revealed, sentence by sentence.",
        "⬜ At a gap the narration pauses and an empty box appears. Type the word you just heard.",
        "↩️ Stuck? Replay the word slowly, replay the sentence, or skip (a skip counts as wrong).",
        "✅ One attempt per gap — the box locks green when right, or shows the correct spelling beside your miss.",
        "📊 Each chapter ends with a score out of 20; the six chapters together make 120 gaps.",
        "🇬🇧 British spelling only — colour, centre, organise, travelling. American spellings are marked wrong.",
      ],
    },
    { kind: "subheading", text: "The six chapters" },
    {
      kind: "bullets",
      items: STORY_CHAPTER_TITLES.map((c) => `Chapter ${c.chapter}: ${c.title}`),
    },
    {
      kind: "review",
      title: "⚡ Listening tips",
      items: [
        "Let the story carry you — the meaning of the sentence tells you which word is missing.",
        "Say the word silently before you type it; if it sounds right, check the tricky letters.",
        "Watch the Word Vault traps: silent letters, doubled letters and the British -our / -re / -ise endings.",
        "Replay the word slowly whenever the sentence moves too fast.",
      ],
    },
  ],
  questions,
};
